/**
 * The SNIP-20 tokens this dashboard knows about.
 *
 * Adapted from dash.scrt.network's `src/utils/config.ts` (MIT), with two
 * deliberate differences:
 *
 * 1. **No code hashes.** The reference hardcodes them, and 21 of its 96 were
 *    stale when checked against the chain — including sSCRT's. A contract query
 *    is encrypted against the code hash, so a stale one does not degrade, it
 *    stops every query on that token dead. Hashes are read from the chain at
 *    runtime instead; see `src/lib/codeHash.ts`.
 * 2. **Axelar assets are flagged.** Their bridge routes have been disabled
 *    since the 2026-06-10 drain, so they are listed (people still hold them)
 *    but never offered as something to bridge.
 *
 * Regenerated by reading the reference config and reconciling every address
 * against secret-4. See docs/chain-facts.md.
 */

import { useCustomTokens } from '@/store/customTokens'

import { SSCRT_ADDRESS, TOKENS, type TokenInfo } from './list'

export { SSCRT_ADDRESS, TOKENS, type TokenInfo }

/**
 * stkd-SCRT — Shade's SCRT staking derivative.
 *
 * A SNIP-20 like the rest, and the only one in this registry that is also a
 * staking position: it can be unbonded back into SCRT rather than only sold.
 * See `src/lib/derivative.ts`.
 */
export const STKD_SCRT_ADDRESS = 'secret1k6u0cy4feepm6pehnz804zmwakuwdapm69tuc4'

const BY_ADDRESS = new Map(TOKENS.map((token) => [token.address, token]))

/**
 * Tokens plus whatever the user has added by address (see `useCustomTokens`).
 *
 * Read lazily rather than imported at module scope: `useCustomTokens` persists
 * to the same localStorage this module would otherwise need to touch directly,
 * and importing the store here would tie the static registry to zustand's
 * init order for no benefit — every caller already goes through a function.
 */
function customTokens(): TokenInfo[] {
  // Deferred import avoided; zustand stores are safe to read outside React.
  return useCustomTokens.getState().tokens
}

export function tokenByAddress(address: string): TokenInfo | undefined {
  return BY_ADDRESS.get(address) ?? customTokens().find((token) => token.address === address)
}

export function tokenImageUrl(token: TokenInfo): string {
  return `/img/tokens/${token.image}`
}

/**
 * What to call a token's private form.
 *
 * The registry lists sSCRT under the ticker `SCRT`, because that is the asset
 * it holds — but the wallet shows the public and the private form side by side,
 * and two rows both reading "SCRT" is the one place that convention stops
 * working. Only this pair needs distinguishing: every other token's public form
 * is an `ibc/…` voucher nobody calls by a ticker.
 */
export function privateSymbol(token: TokenInfo): string {
  return token.address === SSCRT_ADDRESS ? 'sSCRT' : token.symbol
}

/** Every token this dashboard knows about right now, built-in plus custom. */
export function allTokens(): TokenInfo[] {
  return [...TOKENS, ...customTokens()]
}

/** Every contract a permit should cover, so one signature serves the whole app. */
export function allTokenAddresses(): string[] {
  return allTokens().map((token) => token.address)
}

/** Tokens that can currently be bridged — i.e. everything Axelar is not carrying. */
export function bridgeableTokens(): TokenInfo[] {
  return allTokens().filter((token) => !token.axelarAsset)
}
