/**
 * The SNIP-20 tokens this dashboard knows about.
 *
 * Adapted from dash.scrt.network's `src/utils/config.ts` (MIT), with two
 * deliberate differences:
 *
 * 1. **No code hashes.** The reference hardcodes them, and 21 of its 96 were
 *    stale when checked against the chain — including sSCRT's. A contract query
 *    is encrypted against the code hash, so a stale one does not degrade, it
 *    stops every query on that token dead. Hashes are read from the chain at
 *    runtime instead; see `src/lib/codeHash.ts`.
 * 2. **Axelar assets are flagged.** Their bridge routes have been disabled
 *    since the 2026-06-10 drain, so they are listed (people still hold them)
 *    but never offered as something to bridge.
 *
 * Regenerated by reading the reference config and reconciling every address
 * against secret-4. See docs/chain-facts.md.
 */

export interface TokenInfo {
  /** Ticker, as shown. */
  symbol: string
  description?: string
  /** SNIP-20 contract address. The identity of a token throughout this app. */
  address: string
  /** File under /img/tokens/. */
  image: string
  decimals: number
  /** For price lookups. Absent means no price is available — show that, don't invent one. */
  coingeckoId?: string
  /** Issued on Secret rather than bridged in. */
  secretNative?: boolean
  /** Bridged via Axelar; routes disabled since 2026-06-10. */
  axelarAsset?: boolean
}

export const TOKENS: TokenInfo[] = [
  {
    symbol: 'SCRT',
    description: 'Secret',
    address: 'secret1k0jntykt7e4g3y88ltc60czgjuqdy4c9e8fzek',
    image: 'scrt.svg',
    decimals: 6,
    coingeckoId: 'secret'
  },
  {
    symbol: 'AKT',
    description: 'Akash Governance Token',
    address: 'secret168j5f78magfce5r2j4etaytyuy7ftjkh4cndqw',
    image: 'akt.svg',
    decimals: 6,
    coingeckoId: 'akash-network'
  },
  {
    symbol: 'ampBTC',
    description: 'ERIS staked BTC',
    address: 'secret10fnn57cdxqksgqprtvp27d3ykkgyffv9n0gnal',
    image: 'ampwhale.svg',
    decimals: 8
  },
  {
    symbol: 'ampKUJI',
    description: 'ERIS staked KUJI',
    address: 'secret1pf6n6j8xlkxnga5t8w8exdtvcrrjgqms5wdlnj',
    image: 'ampkuji.svg',
    decimals: 6,
    coingeckoId: 'eris-staked-kuji'
  },
  {
    symbol: 'ampLUNA',
    description: 'ERIS staked LUNA',
    address: 'secret1cycwquhh63qmc0qgfe76eed6a6yj5x4vzlu3rc',
    image: 'ampluna.svg',
    decimals: 6,
    coingeckoId: 'eris-amplified-luna'
  },
  {
    symbol: 'ampWHALE',
    description: 'ERIS staked WHALE',
    address: 'secret1jsaftfxnwwmjxccvc3zqaqmkcpp8fjnvvltvq6',
    image: 'ampwhale.svg',
    decimals: 6,
    coingeckoId: 'eris-amplified-whale'
  },
  {
    symbol: 'ANDR',
    description: 'Andromeda Governance Token',
    address: 'secret1dks96n3jz64dyulzjnjazt6cqemr0x0qgn7sd7',
    image: 'andr.png',
    decimals: 6,
    coingeckoId: 'andromeda-2'
  },
  {
    symbol: 'ARCH',
    description: 'Archway Governance Token',
    address: 'secret188z7hncvphw4us4h6uy6vlq4qf20jd2vm2vu8c',
    image: 'archway.svg',
    decimals: 18,
    coingeckoId: 'archway'
  },
  {
    symbol: 'ATOM',
    description: 'Cosmos Hub Governance Token',
    address: 'secret19e75l25r6sa6nhdf4lggjmgpw0vmpfvsw5cnpe',
    image: 'atom.svg',
    decimals: 6,
    coingeckoId: 'cosmos'
  },
  {
    symbol: 'bINJ',
    description: 'Backbone staked INJ',
    address: 'secret17xw4pelwmmhftscrdfntudyv77rkdxvaaelzvs',
    image: 'binj.png',
    decimals: 18
  },
  {
    symbol: 'bKUJI',
    description: 'Backbone staked KUJI',
    address: 'secret1ve536yukullq5rm67gdpssm23wynfv9gcqh6xn',
    image: 'bkuji.png',
    decimals: 6
  },
  {
    symbol: 'BLD',
    description: 'Agoric Governance Token',
    address: 'secret1uxvpq889uxjcpj656yjjexsqa3zqm6ntkyjsjq',
    image: 'bld.svg',
    decimals: 6,
    coingeckoId: 'agoric'
  },
  {
    symbol: 'bLUNA',
    description: 'Backbone staked LUNA',
    address: 'secret1wzqxaa6g6xa27vrwgygex8xurxdjzjtwzlgwy3',
    image: 'bluna.png',
    decimals: 6
  },
  {
    symbol: 'CHEQ',
    description: 'Cheqd Governance Token',
    address: 'secret1lfqlcnpveh6at723h5k2nu4jjqeuz0ukpxxdtt',
    image: 'cheq.svg',
    decimals: 9,
    coingeckoId: 'cheqd-network'
  },
  {
    symbol: 'CMDX',
    description: 'Comdex Governance Token',
    address: 'secret1mndng80tqppllk0qclgcnvccf9urak08e9w2fl',
    image: 'cmdx.svg',
    decimals: 6,
    coingeckoId: 'comdex'
  },
  {
    symbol: 'CMST',
    description: 'Composite USD Stablecoin',
    address: 'secret14l7s0evqw7grxjlesn8yyuk5lexuvkwgpfdxr5',
    image: 'cmst.svg',
    decimals: 6,
    coingeckoId: 'composite'
  },
  {
    symbol: 'CORE',
    description: 'Coreum Governance Token',
    address: 'secret1e8p373krsxva4msh0gdh94lg3rhn7npgmd5g8v',
    image: 'coreum.svg',
    decimals: 6,
    coingeckoId: 'coreum'
  },
  {
    symbol: 'dATOM',
    description: 'Drop ATOM',
    address: 'secret1x3cxgrwymk7yyelf2782r8ay020xyl96zq3rhh',
    image: 'datom.svg',
    decimals: 6,
    coingeckoId: 'cosmos'
  },
  {
    symbol: 'DOT',
    description: 'Polkadot Governance Token',
    address: 'secret1h5d3555tz37crrgl5rppu2np2fhaugq3q8yvv9',
    image: 'dot.svg',
    decimals: 10,
    coingeckoId: 'polkadot'
  },
  {
    symbol: 'DVPN',
    description: 'Sentinel Governance Token',
    address: 'secret15qtw24mpmwkjessr46dnqruq4s4tstzf74jtkf',
    image: 'dvpn.svg',
    decimals: 6,
    coingeckoId: 'sentinel'
  },
  {
    symbol: 'dYdX',
    description: 'dYdX governance token',
    address: 'secret13lndcagy53wfzh69rtv0dex3a7cks0dv5emwke',
    image: 'dydx.svg',
    decimals: 18,
    coingeckoId: 'dydx'
  },
  {
    symbol: 'DYM',
    description: 'Dymension governance token',
    address: 'secret1vfe63g7ndhqq9qu8v4n97fj69rcmr5fy0dun75',
    image: 'dymension.svg',
    decimals: 18,
    coingeckoId: 'dymension'
  },
  {
    symbol: 'ECLIP',
    description: 'Eclipse.fi governance token',
    address: 'secret1r4cldegd4peufgtaxf0qpagclqspeqaf8dm0l9',
    image: 'eclip.svg',
    decimals: 6,
    coingeckoId: 'eclipse-fi'
  },
  {
    symbol: 'FLIX',
    description: 'Omniflix governance token',
    address: 'secret1agpgsn50xjdggzdzd6kl4jz5ueywtkuhnyyhx5',
    image: 'flix.svg',
    decimals: 6,
    coingeckoId: 'omniflix-network'
  },
  {
    symbol: 'GRAV',
    description: 'Gravity Bridge Governance Token',
    address: 'secret1dtghxvrx35nznt8es3fwxrv4qh56tvxv22z79d',
    image: 'grav.svg',
    decimals: 6,
    coingeckoId: 'graviton'
  },
  {
    symbol: 'HARBOR',
    description: 'Harbor Protocol Governance Token',
    address: 'secret1lrlkqhmwkh5y4326akn3hwn6j69f8l5656m43e',
    image: 'harbor.svg',
    decimals: 6,
    coingeckoId: 'harbor-2'
  },
  {
    symbol: 'HUAHUA',
    description: 'Chihuahua Governance Token',
    address: 'secret1ntvxnf5hzhzv8g87wn76ch6yswdujqlgmjh32w',
    image: 'huahua.svg',
    decimals: 6,
    coingeckoId: 'chihuahua-token'
  },
  {
    symbol: 'INJ',
    description: 'Injective Governance Token',
    address: 'secret14706vxakdzkz9a36872cs62vpl5qd84kpwvpew',
    image: 'inj.svg',
    decimals: 18,
    coingeckoId: 'injective-protocol'
  },
  {
    symbol: 'IST',
    description: 'Inter Protocol USD Stablecoin',
    address: 'secret1xmqsk8tnge0atzy4e079h0l2wrgz6splcq0a24',
    image: 'ist.svg',
    decimals: 6,
    coingeckoId: 'inter-stable-token'
  },
  {
    symbol: 'JKL',
    description: 'Jackal Governance Token',
    address: 'secret1sgaz455pmtgld6dequqayrdseq8vy2fc48n8y3',
    image: 'jkl.svg',
    decimals: 6,
    coingeckoId: 'jackal-protocol'
  },
  {
    symbol: 'JUNO',
    description: 'Juno Governance Token',
    address: 'secret1z6e4skg5g9w65u5sqznrmagu05xq8u6zjcdg4a',
    image: 'juno.svg',
    decimals: 6,
    coingeckoId: 'juno-network'
  },
  {
    symbol: 'KAVA',
    description: 'Kava Governance Token',
    address: 'secret1xyhphws090fqs33sxkytmagwynz54eqnpdqfrw',
    image: 'kava.svg',
    decimals: 6,
    coingeckoId: 'kava'
  },
  {
    symbol: 'KUJI',
    description: 'Kujira Governance Token',
    address: 'secret13hvh0rn0rcf5zr486yxlrucvwpzwqu2dsz6zu8',
    image: 'kuji.svg',
    decimals: 6,
    coingeckoId: 'kujira'
  },
  {
    symbol: 'KSM',
    description: 'Kusama Governance Token',
    address: 'secret1n4dp5dk6fufqmaalu9y7pnmk2r0hs7kc66a55f',
    image: 'ksm.svg',
    decimals: 12,
    coingeckoId: 'kusama'
  },
  {
    symbol: 'NLS',
    description: 'Nolus Governance Token',
    address: 'secret1yafpcu9wpauy5ktymggzk9kmsvmce0hkl9p2h7',
    image: 'nolus.svg',
    decimals: 6,
    coingeckoId: 'nolus'
  },
  {
    symbol: 'NSTK',
    description: 'Unstake Governance Token',
    address: 'secret16l5g98d45gqvvn2g79q23h8flfq65cvr9r6c72',
    image: 'nstk.svg',
    decimals: 6,
    coingeckoId: 'unstake-fi'
  },
  {
    symbol: 'NTRN',
    description: 'Neutron Governance Token',
    address: 'secret1k644rvd979wn4erjd5g42uehayjwrq094g5uvj',
    image: 'ntrn.svg',
    decimals: 6,
    coingeckoId: 'neutron-3'
  },
  {
    symbol: 'NYM',
    description: 'Nym Governance Token',
    address: 'secret19gk280z6j9ywt3ln6fmfwfa36dkqeukcwqdw2k',
    image: 'nyx.png',
    decimals: 6,
    coingeckoId: 'nym'
  },
  {
    symbol: 'LUNA',
    description: 'Terra Governance Token',
    address: 'secret149e7c5j7w24pljg6em6zj2p557fuyhg8cnk7z8',
    image: 'luna2.svg',
    decimals: 6,
    coingeckoId: 'terra-luna-2'
  },
  {
    symbol: 'LVN',
    description: 'Levana native Token',
    address: 'secret1swrj0fqza3g98d7agm2nmukjfe44h7f5n8aavp',
    image: 'lvn.svg',
    decimals: 6,
    coingeckoId: 'levana-protocol'
  },
  {
    symbol: 'milkTIA',
    description: 'MilkyWay Staked TIA',
    address: 'secret1h08ru5kul3yajg7tqj6vq9k6rccnfw2yqy8glc',
    image: 'milktia.svg',
    decimals: 6,
    coingeckoId: 'milkyway-staked-tia'
  },
  {
    symbol: 'MNTA',
    description: 'Manta DAO Governance Token',
    address: 'secret15rxfz2w2tallu9gr9zjxj8wav2lnz4gl9pjccj',
    image: 'mnta.svg',
    decimals: 6,
    coingeckoId: 'mantadao'
  },
  {
    symbol: 'ORAI',
    description: 'Oraichain Governance Token',
    address: 'secret1sv0nxz6athw5qm0hsxl90376c9zhrxhhprhjph',
    image: 'orai.svg',
    decimals: 6,
    coingeckoId: 'oraichain-token'
  },
  {
    symbol: 'OSMO',
    description: 'Osmosis Governance Token',
    address: 'secret150jec8mc2hzyyqak4umv6cfevelr0x9p0mjxgg',
    image: 'osmo.svg',
    decimals: 6,
    coingeckoId: 'osmosis'
  },
  {
    symbol: 'PAGE',
    description: 'PageDAO',
    address: 'secret1hhvfxy44e4gp6k7n4e37t7uyqa54dnp68egugg',
    image: 'page.png',
    decimals: 8,
    coingeckoId: 'page'
  },
  {
    symbol: 'PICA',
    description: 'Picasso Token',
    address: 'secret1e0y9vf4xr9wffyxsvlz35jzl5st2srkdl8frac',
    image: 'pica.svg',
    decimals: 12,
    coingeckoId: 'picasso'
  },
  {
    symbol: 'pSTAKE',
    description: 'Persistence pSTAKE',
    address: 'secret1umeg3u5y949vz6jkgq0n4rhefsr84ws3duxmnz',
    image: 'pstake.svg',
    decimals: 18,
    coingeckoId: 'pstake-finance'
  },
  {
    symbol: 'qATOM',
    description: 'Quicksilver ATOM Staking Derivative',
    address: 'secret120cyurq25uvhkc7qjx7t28deuqslprxkc4rrzc',
    image: 'qatom.svg',
    decimals: 6,
    coingeckoId: 'qatom'
  },
  {
    symbol: 'QCK',
    description: 'Quicksilver Governance Token',
    address: 'secret17d8c96kezszpda3r2c5dtkzlkfxw6mtu7q98ka',
    image: 'qck.svg',
    decimals: 6,
    coingeckoId: 'quicksilver'
  },
  {
    symbol: 'USK',
    description: 'Kujira USD Stablecoin',
    address: 'secret1cj2fvj4ap79fl9euz8kqn0k5xlvck0pw9z9xhr',
    image: 'usk.svg',
    decimals: 6,
    coingeckoId: 'kujira'
  },
  {
    symbol: 'USDC',
    description: 'Native USDC Stablecoin from Noble',
    address: 'secret1chsejpk9kfj4vt9ec6xvyguw539gsdtr775us2',
    image: 'usdc.svg',
    decimals: 6,
    coingeckoId: 'usd-coin'
  },
  {
    symbol: 'SAGA',
    description: 'SAGA Governance Token',
    address: 'secret19gmvklys9uywk3lf2e94wqwwc97r3jr5rwa2pa',
    image: 'saga.svg',
    decimals: 6,
    coingeckoId: 'saga-2'
  },
  {
    symbol: 'STARS',
    description: 'Stargaze Governance Token',
    address: 'secret1x0dqckf2khtxyrjwhlkrx9lwwmz44k24vcv2vv',
    image: 'stars.svg',
    decimals: 6,
    coingeckoId: 'stargaze'
  },
  {
    symbol: 'stATOM',
    description: 'Stride ATOM Staking Derivative',
    address: 'secret155w9uxruypsltvqfygh5urghd5v0zc6f9g69sq',
    image: 'statom.svg',
    decimals: 6,
    coingeckoId: 'stride-staked-atom'
  },
  {
    symbol: 'stINJ',
    description: 'Stride INJ Staking Derivative',
    address: 'secret1eurddal3m0tphtapad9awgzcuxwz8ptrdx7h4n',
    image: 'stinj.svg',
    decimals: 18,
    coingeckoId: 'stride-staked-injective'
  },
  {
    symbol: 'stJUNO',
    description: 'Stride JUNO Staking Derivative',
    address: 'secret1097nagcaavlkchl87xkqptww2qkwuvhdnsqs2v',
    image: 'stjuno.svg',
    decimals: 6,
    coingeckoId: 'stride-staked-juno'
  },
  {
    symbol: 'stkATOM',
    description: 'Persistence ATOM Staking Derivative',
    address: 'secret16vjfe24un4z7d3sp9vd0cmmfmz397nh2njpw3e',
    image: 'stkatom.svg',
    decimals: 6,
    coingeckoId: 'stkatom'
  },
  {
    symbol: 'stkDYDX',
    description: 'Persistence dYdX Staking Derivative',
    address: 'secret16dctnuy6lwydw834f4d0t3sw3f6jhav6ryhe4m',
    image: 'stkdydx.svg',
    decimals: 18
  },
  {
    symbol: 'stLUNA',
    description: 'Stride LUNA Staking Derivative',
    address: 'secret1rkgvpck36v2splc203sswdr0fxhyjcng7099a9',
    image: 'stluna.svg',
    decimals: 6,
    coingeckoId: 'stride-staked-luna'
  },
  {
    symbol: 'stOSMO',
    description: 'Stride OSMO Staking Derivative',
    address: 'secret1jrp6z8v679yaq65rndsr970mhaxzgfkymvc58g',
    image: 'stosmo.svg',
    decimals: 6,
    coingeckoId: 'stride-staked-osmo'
  },
  {
    symbol: 'STRD',
    description: 'Stride Governance Token',
    address: 'secret1rfhgs3ryqt7makakr2qw9zsqq4h5wdqawfa2aa',
    image: 'stride.svg',
    decimals: 6,
    coingeckoId: 'stride'
  },
  {
    symbol: 'stTIA',
    description: 'Stride TIA Staking Derivative',
    address: 'secret1l5d0vncwnlln0tz0m4tp9rgm740xl7th6es0q0',
    image: 'sttia.svg',
    decimals: 6,
    coingeckoId: 'stride-staked-tia'
  },
  {
    symbol: 'SWTH',
    description: 'Carbon Governance Token',
    address: 'secret1gech42jfcdke92tf9ltscpq7x0al8j7gkce030',
    image: 'swth.svg',
    decimals: 8,
    coingeckoId: 'switcheo'
  },
  {
    symbol: 'SYN',
    description: 'Galactic Syndicate Governance Token',
    address: 'secret1hjcv25hpgqtpwn90tz7pttr9fyz7l9pngzz8rl',
    image: 'syn.png',
    decimals: 6
  },
  {
    symbol: 'TIA',
    description: 'Celestia Governance Token',
    address: 'secret1s9h6mrp4k9gll4zfv5h78ll68hdq8ml7jrnn20',
    image: 'celestia.svg',
    decimals: 6,
    coingeckoId: 'celestia'
  },
  {
    symbol: 'UMEE',
    description: 'UX Chain Governance Token',
    address: 'secret1f6yg0typy608r567xekwyn3qf0k902llue9w2l',
    image: 'umee.svg',
    decimals: 6,
    coingeckoId: 'umee'
  },
  {
    symbol: 'USDT',
    description: 'Native USDT from Kava',
    address: 'secret1htd6s29m2j9h45knwkyucz98m306n32hx8dww3',
    image: 'usdt.svg',
    decimals: 6,
    coingeckoId: 'tether'
  },
  {
    symbol: 'WBTC',
    description: 'Wrapped Bitcoin from Osmosis',
    address: 'secret1v2kgmfwgd2an0l5ddralajg5wfdkemxl2vg4jp',
    image: 'wbtc.svg',
    decimals: 8,
    coingeckoId: 'bitcoin'
  },
  {
    symbol: 'WHALE',
    description: 'Migaloo Governance Token',
    address: 'secret1pcftk3ny87zm6thuxyfrtrlm2t8yev5unuvx6c',
    image: 'migaloo.svg',
    decimals: 6,
    coingeckoId: 'white-whale'
  },
  {
    symbol: 'wstETH',
    description: 'Wrapped Lido stETH from Neutron',
    address: 'secret1xx6m5c7d92h75evkmxqqe2xe5sk5qcqqs9t8ar',
    image: 'wsteth.svg',
    decimals: 18,
    coingeckoId: 'wrapped-steth'
  },
  {
    symbol: 'XPRT',
    description: 'Persistence Governance Token',
    address: 'secret1gnrrqjj5e2pwn4g262xjyypptu0ge3z3tps3nn',
    image: 'xprt.svg',
    decimals: 6,
    coingeckoId: 'persistence'
  },
  {
    symbol: 'XRP',
    description: 'Ripple XRP via Coreum',
    address: 'secret1gqn3k7792h9vqpydvq6hnh3wr9lqg3s9j6hzy6',
    image: 'xrp.svg',
    decimals: 6,
    coingeckoId: 'ripple'
  },
  {
    symbol: 'ALTER',
    description: 'ALTER dApp Token',
    address: 'secret17ljp7wwesff85ewt8xlauxjt7zrlr2hh27wgvr',
    image: 'alter.svg',
    decimals: 6,
    coingeckoId: 'alter',
    secretNative: true
  },
  {
    symbol: 'ATOM/dATOM LP',
    description: 'ShadeSwap LP token for ATOM-dATOM',
    address: 'secret1gddp7wlpkups509u76dca550xuxk6ckjru5x54',
    image: 'atom_datom_lp.svg',
    decimals: 6,
    secretNative: true
  },
  {
    symbol: 'ATOM/stATOM LP',
    description: 'ShadeSwap LP token for ATOM-stATOM',
    address: 'secret1kmjr03phgn4v4u0altvvuc53lfmy033wmvddy5',
    image: 'atom_statom_lp.svg',
    decimals: 6,
    secretNative: true
  },
  {
    symbol: 'AMBER',
    description: 'Amber DAO Token (very rare)',
    address: 'secret1s09x2xvfd2lp2skgzm29w2xtena7s8fq98v852',
    image: 'amber.jpg',
    decimals: 6,
    coingeckoId: 'amberdao',
    secretNative: true
  },
  {
    symbol: 'dSHD',
    description: 'Shade Protocol SHD Staking Derivative',
    address: 'secret1fcef2mpuzw7py0e6eplrm06t5n6n2xfljvuzaq',
    image: 'dshd.svg',
    decimals: 8,
    coingeckoId: 'shade-protocol',
    secretNative: true
  },
  {
    symbol: 'FINA',
    description: 'Fina.cash Token',
    address: 'secret1s3z9xkpdsrhk86300tqnv6u466jmdmlegew2ve',
    image: 'fina.png',
    decimals: 6,
    coingeckoId: 'fina',
    secretNative: true
  },
  {
    symbol: 'SHD',
    description: 'Shade Protocol Governance Token',
    address: 'secret153wu605vvp934xhd4k9dtd640zsep5jkesstdm',
    image: 'shd.svg',
    decimals: 8,
    coingeckoId: 'shade-protocol',
    secretNative: true
  },
  {
    symbol: 'SHILL',
    description: 'Shillstake Governance Token',
    address: 'secret197dvnt9yjxwn8sjdlx05f7zuk27lsdxtfnwxse',
    image: 'shill.svg',
    decimals: 6,
    secretNative: true
  },
  {
    symbol: 'SILK',
    description: 'Shade Protocol Privacy-Preserving Stablecoin',
    address: 'secret1fl449muk5yq8dlad7a22nje4p5d2pnsgymhjfd',
    image: 'silk.svg',
    decimals: 6,
    coingeckoId: 'silk-bcec1136-561c-4706-a42c-8b67d0d7f7d2',
    secretNative: true
  },
  {
    symbol: 'stkd-SCRT',
    description: 'Shade Protocol SCRT Staking Derivative',
    address: 'secret1k6u0cy4feepm6pehnz804zmwakuwdapm69tuc4',
    image: 'stkd-scrt.svg',
    decimals: 6,
    coingeckoId: 'stkd-scrt',
    secretNative: true
  },
  {
    symbol: 'xATOM',
    description: 'Lent Secret ATOM from Shade',
    address: 'secret1ydpmlhqat9s2qxwc5ldyms8yp53nhqcvh6mz3c',
    image: 'atom.svg',
    decimals: 6,
    coingeckoId: 'cosmos',
    secretNative: true
  },
  {
    symbol: 'stATOM/xstATOM LP',
    description: 'stATOM/xstATOM LP from Shade Protocol',
    address: 'secret179m85kh3vq6cler57na6c6m5d3lwm3zj0m2v9u',
    image: 'dshd.svg',
    decimals: 6,
    secretNative: true
  },
  {
    symbol: 'USDC.axl',
    description: 'USDC stablecoin from Axelar',
    address: 'secret1vkq022x4q8t8kx9de3r84u669l65xnwf2lg3e6',
    image: 'usdc.svg',
    decimals: 6,
    coingeckoId: 'usd-coin',
    axelarAsset: true
  },
  {
    symbol: 'AXL',
    description: 'Axelar Governance Token',
    address: 'secret1vcau4rkn7mvfwl8hf0dqa9p0jr59983e3qqe3z',
    image: 'axl.svg',
    decimals: 6,
    coingeckoId: 'axelar',
    axelarAsset: true
  },
  {
    symbol: 'WETH',
    description: 'Wrapped ETH from Axelar',
    address: 'secret139qfh3nmuzfgwsx2npnmnjl4hrvj3xq5rmq8a0',
    image: 'weth.svg',
    decimals: 18,
    coingeckoId: 'ethereum',
    axelarAsset: true
  },
  {
    symbol: 'wstETH.axl',
    description: 'wstETH from Axelar',
    address: 'secret148jzxkagwe0xulf8jt3sw4nuh2shdh788z3gyd',
    image: 'wsteth.svg',
    decimals: 18,
    coingeckoId: 'bridged-wrapped-steth-axelar',
    axelarAsset: true
  },
  {
    symbol: 'WBTC.axl',
    description: 'Wrapped Bitcoin from Axelar',
    address: 'secret1guyayjwg5f84daaxl7w84skd8naxvq8vz9upqx',
    image: 'wbtc.svg',
    decimals: 8,
    coingeckoId: 'bitcoin',
    axelarAsset: true
  },
  {
    symbol: 'WBNB',
    description: 'Wrapped Binance Coin from Axelar',
    address: 'secret19xsac2kstky8nhgvvz257uszt44g0cu6ycd5e4',
    image: 'wbnb.svg',
    decimals: 18,
    coingeckoId: 'binancecoin',
    axelarAsset: true
  },
  {
    symbol: 'BUSD',
    description: 'Binance USD from Axelar',
    address: 'secret1t642ayn9rhl5q9vuh4n2jkx0gpa9r6c3sl96te',
    image: 'abusd.svg',
    decimals: 18,
    coingeckoId: 'busd',
    axelarAsset: true
  },
  {
    symbol: 'DAI',
    description: 'DAI from Axelar',
    address: 'secret1c2prkwd8e6ratk42l4vrnwz34knfju6hmp7mg7',
    image: 'adai.svg',
    decimals: 18,
    coingeckoId: 'dai',
    axelarAsset: true
  },
  {
    symbol: 'LINK',
    description: 'LINK from Axelar',
    address: 'secret1walthx26qaas50nwzg2rsqttlkf58q3hvjha5k',
    image: 'alink.svg',
    decimals: 18,
    coingeckoId: 'chainlink',
    axelarAsset: true
  },
  {
    symbol: 'UNI',
    description: 'UNI from Axelar',
    address: 'secret1egqlkasa6xe6efmfp9562sfj07lq44z7jngu5k',
    image: 'auni.svg',
    decimals: 18,
    coingeckoId: 'uniswap',
    axelarAsset: true
  },
  {
    symbol: 'USDT.axl',
    description: 'USDT stablecoin from Axelar',
    address: 'secret1wk5j2cntwg2fgklf0uta3tlkvt87alfj7kepuw',
    image: 'usdt.svg',
    decimals: 6,
    coingeckoId: 'tether',
    axelarAsset: true
  },
  {
    symbol: 'FRAX',
    description: 'FRAX from Axelar',
    address: 'secret16e230j6qm5u5q30pcc6qv726ae30ak6lzq0zvf',
    image: 'afrax.svg',
    decimals: 18,
    coingeckoId: 'frax',
    axelarAsset: true
  }
]

/** sSCRT — wrapped SCRT, and the token most of this app's flows touch. */
export const SSCRT_ADDRESS = 'secret1k0jntykt7e4g3y88ltc60czgjuqdy4c9e8fzek'

const BY_ADDRESS = new Map(TOKENS.map((token) => [token.address, token]))

export function tokenByAddress(address: string): TokenInfo | undefined {
  return BY_ADDRESS.get(address)
}

export function tokenImageUrl(token: TokenInfo): string {
  return `/img/tokens/${token.image}`
}

/** Every contract a permit should cover, so one signature serves the whole app. */
export function allTokenAddresses(): string[] {
  return TOKENS.map((token) => token.address)
}

/** Tokens that can currently be bridged — i.e. everything Axelar is not carrying. */
export function bridgeableTokens(): TokenInfo[] {
  return TOKENS.filter((token) => !token.axelarAsset)
}
